#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/utils/dependencies.rb'
StartUp.execute

def handle_history(line)
  unless Readline::HISTORY.to_a.empty?
    return Readline::HISTORY.pop if /^\s*$/ =~ line
    return Readline::HISTORY.pop if Readline::HISTORY.to_a[-2] == line
  end

  File.write('.postwoman_history', "#{line}\n", mode: 'a')
end

while (line = Readline.readline('> ', true))
  handle_history(line)

  load_loaders
  attempt_command(line)
end
